apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "webapp.fullname" . }}{{ .Values.webapp1.containerName}}
  namespace: {{ .Values.namespace }}
  labels:
    component: {{ template "webapp.fullname" . }}
spec:
  replicas: {{ .Values.webapp1.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "webapp.fullname" . }}
  template:
    metadata:
      labels:
        component: {{ template "webapp.fullname" . }}
    spec:
      containers:
      - name: {{ .Values.webapp1.containerName }}
        image: {{ .Values.webapp1.repository }}:{{ .Values.webapp1.tag }}
        ports:
        - containerPort: {{ .Values.webapp1.service.containerport }}
        env:
        - name: Stack
          value: {{ .Values.webapp1.stack }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "webapp.fullname" . }}{{ .Values.webapp1.containerName}}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
   - port: {{ .Values.webapp1.service.port }}
     targetPort: {{ .Values.webapp1.service.containerport }}
  selector:
    component: {{ template "webapp.fullname" . }}
